#include <iostream>
using namespace std;
main()
{
int num1;
int num2;
int num3;
int num4;
int num5;
int num6;
int num7;
int num8;
int num9;
int num10;
int num11;
int num12;
int num13;
int num14;
int num15;
int result1;
int result2;
int result3;
int result4;
int result5;
cout <<"Enter 1st number : ";
cin >>num1;
cout <<"Enter 2nd number : ";
cin >>num2;
cout <<"Enter 3rd number : ";
cin >>num3;
cout <<"Enter 4th number : ";
cin >>num4;
cout <<"Enter 5th number : ";
cin >>num5;
cout <<"Enter 6th number : ";
cin >>num6;
cout <<"Enter 7th number : ";
cin >>num7;
cout <<"Enter 8th number : ";
cin >>num8;
cout <<"Enter 9th number : ";
cin >>num9;
cout <<"Enter 10th number : ";
cin >>num10;
cout <<"Enter 11th number : ";
cin >>num11;
cout <<"Enter 12th number : ";
cin >>num12;
cout <<"Enter 13th number : ";
cin >>num13;
cout <<"Enter 14th number : ";
cin >>num14;
cout <<"Enter 15 number : ";
cin >>num15;
result1= num1+num2+num3+num4+num5;
result2= num6*num7*num8*num9*num10;
result3= num11-num12-num13-num14-num15;
result4= result1+result2;
result5= result4-result3;
cout<< "Total : ";
cout <<result5;
}

